Repository team-suwiki/suwiki-android, pull requests merged in 2023-12, with the labels that each got.

#39 Feature/selections component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/Sample.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/dropdown/SuwikiDropDown.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSlider.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderThumb.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderThumbWithLabel.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderTrack.kt
  core/designsystem/src/main/res/drawable/ic_dropdown_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_slider_thumb_hovered.xml
Labels: feature

#41 Feature/chips label component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiColorChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiContainedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiOutlinedChip.kt
  core/designsystem/src/main/res/drawable/ic_color_checked_chip.xml
  core/designsystem/src/main/res/drawable/ic_color_chip.xml
  presentation/src/main/res/values/strings.xml
Labels: feature

#46 Feature/#30 button component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/Button.kt
Labels: feature

#51 Feature/#47 design system alert
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/Button.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/dialog/SuwikiDialog.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/toast/SuwikiToastView.kt
Labels: feature

#52 Feature/#33 coroutine dispatchers di
  app-compose/build.gradle.kts
  core/android/.gitignore
  core/android/build.gradle.kts
  core/android/consumer-rules.pro
  core/android/proguard-rules.pro
  core/android/src/main/AndroidManifest.xml
  core/android/src/main/java/com/suwiki/core/android/Dispatcher.kt
  core/android/src/main/java/com/suwiki/core/android/DispatchersModule.kt
  core/database/src/main/java/com/suwiki/core/database/di/DataStoreModule.kt
  core/security/src/main/java/com/suwiki/core/security/di/DataStoreModule.kt
  data/openmajor/src/main/java/com/suwiki/data/openmajor/repository/OpenMajorRepositoryImpl.kt
  data/timetable/src/main/java/com/suwiki/data/timetable/repository/OpenLectureRepositoryImpl.kt
  local/openmajor/build.gradle.kts
  local/openmajor/src/main/java/com/suwiki/local/openmajor/datasource/LocalOpenMajorDataSourceImpl.kt
  local/timetable/build.gradle.kts
  local/timetable/src/main/java/com.suwiki.local.timetable/datasource/LocalOpenLectureDatasourceImpl.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/datasource/LocalTimetableDatasourceImpl.kt
  presentation/src/main/java/com/mangbaam/presentation/MainActivity.kt
  settings.gradle.kts
Labels: enhancement, chore

#49 Feature/align filter component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiContainedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiOutlinedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/filter/SuwikiFilterButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/filter/SuwikiFilterContainer.kt
  core/designsystem/src/main/res/drawable/ic_align_checked.xml
  core/designsystem/src/main/res/drawable/ic_filter_arrow_down.xml
  core/designsystem/src/main/res/drawable/ic_filter_stared.xml
Labels: feature

#55 Feature/#35 timetable component
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/Common.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/Timetable.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/cell/ClassCell.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/cell/ELearningCell.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/cell/EmptyCell.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/column/ClassColumn.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/column/TimeColumn.kt
  core/designsystem/src/main/res/drawable/ic_timetable_add.xml
  core/designsystem/src/main/res/drawable/ic_timetable_hamburger.xml
  core/designsystem/src/main/res/drawable/ic_timetable_setting.xml
  core/designsystem/src/main/res/values/strings.xml
  core/model/build.gradle.kts
  core/model/src/main/java/com/suwiki/core/model/timetable/Enums.kt
  core/model/src/main/java/com/suwiki/core/model/timetable/Timetable.kt
  core/model/src/main/java/com/suwiki/core/model/timetable/TimetableCell.kt
  gradle/libs.versions.toml
  local/timetable/src/main/java/com.suwiki.local.timetable/converter/TimetableEntity.kt
Labels: feature

#56 Feature/#34 update readme
  README.md
  docs/core_module.png
  docs/entire_module_graph.png
Labels: docs

#57 Feature/#53 design system card
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/BasicButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiClassInformationCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiClassReviewCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiReviewGradeCard.kt
  core/designsystem/src/main/res/drawable/ic_star.xml
  core/designsystem/src/main/res/values/strings.xml
Labels: feature

#58 Feature/#54 navigationbar component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/appbar/SuwikiAppBarWithTextButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/appbar/SuwikiAppBarWithTitle.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/appbar/SuwikiEvaluationAppBar.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/appbar/SuwikiTimeTableAppBar.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiColorChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiContainedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiOutlinedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/filter/SuwikiFilterButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/filter/SuwikiFilterContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/tapbar/SuwikiTabBar.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/tapbar/SuwikiTabBarItem.kt
  core/designsystem/src/main/res/drawable/ic_appbar_add.xml
  core/designsystem/src/main/res/drawable/ic_appbar_arrow_left.xml
  core/designsystem/src/main/res/drawable/ic_appbar_close_mark.xml
  core/designsystem/src/main/res/drawable/ic_appbar_list.xml
  core/designsystem/src/main/res/drawable/ic_appbar_setting.xml
Labels: feature

#61 Refactor/#45 design system
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/TextFieldClearButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiColorChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiContainedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiOutlinedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/dropdown/SuwikiDropDown.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/searchbar/SuwikiSearchBar.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/searchbar/SuwikiSearchBarWithFilter.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSlider.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderThumb.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderThumbWithLabel.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSliderTrack.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/material/Slider.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/material/SliderState.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiTextFieldRegular.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiTextFieldReview.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiTextFieldSmall.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/shadow/BottomNavigationShadow.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/shadow/CardShadow.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/shadow/SuwikiShadow.kt
Labels: refactor

#64 Feature/#59 bottomnavigation component
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomnavigation/SuwikiBottomNavigation.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomnavigation/SuwikiBottomNavigationItem.kt
  core/designsystem/src/main/res/drawable/ic_bottom_navigation_evaluation.xml
Labels: feature

#74 Feature/#71 login
  app-compose/build.gradle.kts
  app-compose/src/main/AndroidManifest.xml
  app-compose/src/main/ic_logo-playstore.png
  core/android/src/main/java/com/suwiki/core/android/ThrowUnknownException.kt
  core/designsystem/src/main/ic_logo-playstore.png
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/dialog/SuwikiDialog.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/loading/LoadingScreen.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiRegularTextField.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiReviewInputBox.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiSmallTextField.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/theme/Typography.kt
  core/designsystem/src/main/res/drawable/ic_eye_off.xml
  core/designsystem/src/main/res/drawable/ic_eye_on.xml
  core/designsystem/src/main/res/drawable/ic_logo.xml
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_logo.xml
  core/designsystem/src/main/res/mipmap-anydpi-v26/ic_logo_round.xml
  core/designsystem/src/main/res/mipmap-hdpi/ic_logo.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_logo_foreground.webp
  core/designsystem/src/main/res/mipmap-hdpi/ic_logo_round.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_logo.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_logo_foreground.webp
  core/designsystem/src/main/res/mipmap-mdpi/ic_logo_round.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_logo.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_logo_foreground.webp
  core/designsystem/src/main/res/mipmap-xhdpi/ic_logo_round.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_logo.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_logo_foreground.webp
  core/designsystem/src/main/res/mipmap-xxhdpi/ic_logo_round.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_logo.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_logo_foreground.webp
  core/designsystem/src/main/res/mipmap-xxxhdpi/ic_logo_round.webp
  core/designsystem/src/main/res/values/ic_logo_background.xml
  core/network/build.gradle.kts
  core/network/src/main/java/com/suwiki/core/network/di/NetworkModule.kt
  data/user/src/main/java/com/suwiki/data/user/repository/UserRepositoryImpl.kt
  feature/lectureevaluation/viewerreporter/build.gradle.kts
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/OnboardingBottomSheet.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/OnboardingPager.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/navigation/LectureEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/src/main/res/drawable/ic_onboarding1.png
  feature/lectureevaluation/viewerreporter/src/main/res/drawable/ic_onboarding2.png
  feature/lectureevaluation/viewerreporter/src/main/res/values/strings.xml
  feature/login/src/main/java/com/suwiki/feature/login/LoginContract.kt
  feature/login/src/main/java/com/suwiki/feature/login/LoginScreen.kt
  feature/login/src/main/java/com/suwiki/feature/login/LoginViewModel.kt
  feature/login/src/main/java/com/suwiki/feature/login/navigation/LoginNavigation.kt
  feature/login/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainContract.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainViewModel.kt
  feature/navigator/src/main/res/values/strings.xml
  gradle/libs.versions.toml
Labels: feature

#76 Feature/#73 my home&notice
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/appbar/SuwikiAppBarWithTitle.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiBottomSheet.kt
  core/model/src/main/java/com/suwiki/core/model/notice/Notice.kt
  core/model/src/main/java/com/suwiki/core/model/notice/NoticeDetail.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/navigation/MyInfoNavigation.kt
  feature/myinfo/src/main/res/drawable/ic_my_info_comment.xml
  feature/myinfo/src/main/res/drawable/ic_my_info_notice.xml
  feature/myinfo/src/main/res/drawable/ic_my_info_point.xml
  feature/myinfo/src/main/res/drawable/ic_my_info_setting.xml
  feature/myinfo/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeContract.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeDetailContract.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeDetailScreen.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeDetailViewModel.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/navigation/NoticeNavigation.kt
  feature/notice/src/main/res/values/strings.xml
Labels: feature

#78 Feature/#75 open major
  core/android/build.gradle.kts
  core/android/src/main/java/com/suwiki/core/android/ThrowUnknownException.kt
  core/designsystem/build.gradle.kts
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/tabbar/SuwikiTabBar.kt
  core/model/src/main/java/com/suwiki/core/model/notice/NoticeDetail.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/Flow.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/LazyListState.kt
  data/user/src/main/java/com/suwiki/data/user/repository/UserRepositoryImpl.kt
  domain/openmajor/src/main/java/com/suwiki/domain/openmajor/usecase/GetOpenMajorListUseCase.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/navigation/LectureEvaluationNavigation.kt
  feature/login/src/main/java/com/suwiki/feature/login/LoginScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainViewModel.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeContract.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeScreen.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeViewModel.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/detail/NoticeDetailContract.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/detail/NoticeDetailScreen.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/detail/NoticeDetailViewModel.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/navigation/NoticeNavigation.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/OpenMajorContract.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/OpenMajorScreen.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/OpenMajorViewModel.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/component/OpenMajorContainer.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/model/OpenMajor.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/model/OpenMajorTap.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/navigation/OpenMajorNavigation.kt
  feature/openmajor/src/main/res/values/strings.xml
  remote/notice/src/main/java/com/suwiki/remote/notice/api/NoticeApi.kt
  remote/openmajor/src/main/java/com/suwiki/remote/openmajor/api/MajorApi.kt
  remote/openmajor/src/main/java/com/suwiki/remote/openmajor/datasource/RemoteOpenMajorDataSourceImpl.kt
  remote/openmajor/src/main/java/com/suwiki/remote/openmajor/request/BookmarkMajorRequest.kt
Labels: feature
