Repository team-suwiki/suwiki-android, pull requests merged in 2024-01, with the labels that each got.

#81 Feature/#80 signup
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiAgreementBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiSelectionContainer.kt
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/java/com/suwiki/core/ui/util/Consts.kt
  core/ui/src/main/java/com/suwiki/core/ui/util/LaunchedEffectWithLifecycle.kt
  core/ui/src/main/res/values/strings.xml
  data/signup/src/main/java/com/suwiki/data/signup/di/RepositoryModule.kt
  data/signup/src/main/java/com/suwiki/data/signup/repository/SignupRepositoryImpl.kt
  domain/signup/src/main/java/com/suwiki/domain/signup/repository/SignupRepository.kt
  domain/signup/src/main/java/com/suwiki/domain/signup/usecase/CheckEmailOverlapUseCase.kt
  domain/signup/src/main/java/com/suwiki/domain/signup/usecase/CheckIdOverlapUseCase.kt
  domain/signup/src/main/java/com/suwiki/domain/signup/usecase/SignupUseCase.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/navigation/LectureEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/src/main/res/values/strings.xml
  feature/login/src/main/java/com/suwiki/feature/login/LoginContract.kt
  feature/login/src/main/java/com/suwiki/feature/login/LoginScreen.kt
  feature/login/src/main/java/com/suwiki/feature/login/LoginViewModel.kt
  feature/login/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/complete/SignupCompleteContract.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/complete/SignupCompleteScreen.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/complete/SignupCompleteViewModel.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/navigation/SignupNavigation.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/signup/SignupContract.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/signup/SignupScreen.kt
  feature/signup/src/main/java/com/suwiki/feature/signup/signup/SignupViewModel.kt
  feature/signup/src/main/res/drawable/ic_signup_complete.png
  feature/signup/src/main/res/values/strings.xml
Labels: feature

#84 Feature/#77 my review
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/chips/SuwikiContainedChip.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiSelectionContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/slider/SuwikiSlider.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/textfield/SuwikiReviewInputBox.kt
  core/model/src/main/java/com/suwiki/core/model/enums/EvaluationLevel.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/exam/MyExamEvaluation.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/LectureInfo.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/MyLectureEvaluation.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/Enums.kt
  core/ui/src/main/res/values/strings.xml
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/myinfo/build.gradle.kts
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/MyEvaluationContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/MyEvaluationScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/MyEvaluationViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/examevaluation/MyExamEvaluationEditViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/examevaluation/MyExamEvalutionEditContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/examevaluation/MyExamEvalutionEditScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/lectureevaluation/MyLectureEvaluationEditContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/lectureevaluation/MyLectureEvaluationEditScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/lectureevaluation/MyLectureEvaluationEditViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myevaluation/model/MyEvaluationTab.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/navigation/MyInfoNavigation.kt
  feature/myinfo/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
Labels: feature

#87 Feature/#85 timetable migration
  app-compose/build.gradle.kts
  core/database/build.gradle.kts
  core/database/src/main/java/com/suwiki/core/database/database/TimetableDatabase.kt
  core/database/src/main/java/com/suwiki/core/database/database/converter/TimetableCellListConverter.kt
  core/database/src/main/java/com/suwiki/core/database/database/migration/TimetableMigration.kt
  core/database/src/main/java/com/suwiki/core/database/di/DatabaseModule.kt
  core/database/src/main/java/com/suwiki/core/database/model/TimetableEntity.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/timetable/cell/ClassCell.kt
  core/model/build.gradle.kts
  core/model/src/main/java/com/suwiki/core/model/timetable/Enums.kt
  core/model/src/main/java/com/suwiki/core/model/timetable/Timetable.kt
  core/model/src/main/java/com/suwiki/core/model/timetable/TimetableCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/TimetableViewModel.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/converter/Timetable.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/converter/TimetableEntity.kt
  schemas/com.suwiki.core.database.database.TimetableDatabase/1.json
  schemas/com.suwiki.core.database.database.TimetableDatabase/2.json
Labels: feature

#93 Feature/#92 open lecture list
  core/database/src/main/java/com/suwiki/core/database/dao/OpenLectureDao.kt
  core/database/src/main/java/com/suwiki/core/database/database/OpenLectureDatabase.kt
  core/database/src/main/java/com/suwiki/core/database/di/DaoModule.kt
  core/database/src/main/java/com/suwiki/core/database/di/DatabaseModule.kt
  core/database/src/main/java/com/suwiki/core/database/model/OpenLectureEntity.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/button/SuwikiContainedButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiClassInformationCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/searchbar/SuwikiSearchBar.kt
  core/designsystem/src/main/res/values/strings.xml
  core/model/src/main/java/com/suwiki/core/model/timetable/OpenLecture.kt
  core/network/build.gradle.kts
  core/network/src/main/java/com/suwiki/core/network/di/DatabaseModule.kt
  core/ui/src/main/res/drawable/ic_dropdown_arrow_down.xml
  core/ui/src/main/res/values/strings.xml
  data/timetable/src/main/java/com/suwiki/data/timetable/datasource/LocalOpenLectureDatasource.kt
  data/timetable/src/main/java/com/suwiki/data/timetable/datasource/RemoteOpenLectureDataSource.kt
  data/timetable/src/main/java/com/suwiki/data/timetable/repository/OpenLectureRepositoryImpl.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/repository/OpenLectureRepository.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/GetOpenLectureListUseCase.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/OpenMajorScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/addcell/AddTimetableCellContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/addcell/AddTimetableCellScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/addcell/AddTimetableCellViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/addcell/model/SchoolLevel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/navigation/TimetableNavigation.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/TimetableAppbar.kt
  feature/timetable/src/main/res/values/strings.xml
  gradle/libs.versions.toml
  local/timetable/src/main/java/com.suwiki.local.timetable/converter/OpenLecture.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/converter/OpenLectureEntity.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/datasource/LocalOpenLectureDatasourceImpl.kt
  local/timetable/src/main/java/com.suwiki.local.timetable/di/LocalDataSourceModule.kt
  remote/timetable/build.gradle.kts
  remote/timetable/src/main/java/com.suwiki.remote.timetable/api/OpenLectureApi.kt
  remote/timetable/src/main/java/com.suwiki.remote.timetable/datasource/RemoteOpenLectureDataSourceImpl.kt
  remote/timetable/src/main/java/com.suwiki.remote.timetable/di/ApiModule.kt
  remote/timetable/src/main/java/com.suwiki.remote.timetable/response/OpenLectureResponse.kt
Labels: feature

#101 Feature/#99 timetable list cell edit
  core/database/src/main/java/com/suwiki/core/database/dao/TimeTableDao.kt
  core/model/src/main/java/com/suwiki/core/model/timetable/Timetable.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/Etc.kt
  core/ui/src/main/res/values/strings.xml
  data/timetable/src/main/java/com/suwiki/data/timetable/datasource/LocalTimetableDataSource.kt
  data/timetable/src/main/java/com/suwiki/data/timetable/repository/TimetableRepositoryImpl.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/repository/TimetableRepository.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/DeleteTimetableCellUseCase.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/DeleteTimetableUseCase.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/GetTimetableCellTypeUseCase.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/SetTimetableCellTypeUseCase.kt
  domain/timetable/src/main/java/com/suwiki/domain/timetable/usecase/UpdateTimetableCellUseCase.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/addcell/AddCellContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/celleditor/CellEditorContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/celleditor/CellEditorScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/celleditor/CellEditorViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/createtimetable/CreateTimetableContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/createtimetable/CreateTimetableViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/navigation/TimetableNavigation.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/navigation/argument/CellEditorArgument.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/navigation/argument/TimetableEditorArgument.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/OpenLectureContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/OpenLectureScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/OpenLectureViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/EditTimetableCellBottomSheet.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/Timetable.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/cell/ClassCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetableeditor/TimetableEditorContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetableeditor/TimetableEditorScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetableeditor/TimetableEditorViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetablelist/TimetableListContract.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetablelist/TimetableListScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetablelist/TimetableListViewModel.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetablelist/component/TimetableEditContainer.kt
  feature/timetable/src/main/res/values/strings.xml
  local/timetable/src/main/java/com.suwiki.local.timetable/datasource/LocalTimetableDatasourceImpl.kt
Labels: feature

#102 Feature/#98 my point&ban history
  data/user/src/main/java/com/suwiki/data/user/datasource/RemoteUserDataSource.kt
  data/user/src/main/java/com/suwiki/data/user/repository/UserRepositoryImpl.kt
  domain/user/src/main/java/com/suwiki/domain/user/repository/UserRepository.kt
  domain/user/src/main/java/com/suwiki/domain/user/usecase/GetBanHistoryUseCase.kt
  domain/user/src/main/java/com/suwiki/domain/user/usecase/GetBlackListUseCase.kt
  feature/myinfo/build.gradle.kts
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/mypoint/MyPointContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/mypoint/MyPointScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/mypoint/MyPointViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/navigation/MyInfoNavigation.kt
  feature/myinfo/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  remote/user/src/main/java/com/suwiki/remote/user/api/UserApi.kt
  remote/user/src/main/java/com/suwiki/remote/user/datasource/RemoteUserDataSourceImpl.kt
  remote/user/src/main/java/com/suwiki/remote/user/response/BanHistoryResponse.kt
  remote/user/src/main/java/com/suwiki/remote/user/response/BlackListResponse.kt
Labels: feature

#105 Feature/#104 timetable widget
  feature/timetable/build.gradle.kts
  feature/timetable/src/main/AndroidManifest.xml
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/TimetableScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/Timetable.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/cell/ClassCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/column/ClassColumn.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/SendWidgetUpdateCommand.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/TimetableWidget.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/TimetableWidgetReceiver.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/Common.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/GlanceTimetable.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/cell/GlanceClassCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/cell/GlanceELearningCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/cell/GlanceEmptyCell.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/column/GlanceClassColumn.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/column/GlanceTimeColumn.kt
  feature/timetable/src/main/res/xml/timetable_widget_info.xml
  gradle/libs.versions.toml
Labels: feature

#108 Feature/#107 my page
  app-compose/build.gradle.kts
  build-logic/convention/src/main/java/com/kunize/convention/KotlinAndroid.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/Context.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/Etc.kt
  feature/lectureevaluation/editor/src/main/res/values/strings.xml
  feature/myinfo/build.gradle.kts
  feature/myinfo/src/main/AndroidManifest.xml
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/MyInfoViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryContract.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myaccount/MyAccountScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myaccount/MyAccountViewModel.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/navigation/MyInfoNavigation.kt
  feature/myinfo/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  gradle.properties
Labels: feature

#112 Feature/#103 lecture evaluation detail
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiClassReviewCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiReviewGradeCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiExamReviewContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiUserReviewContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/tabbar/SuwikiTabBar.kt
  core/model/src/main/java/com/suwiki/core/model/enums/EvaluationLevel.kt
  core/model/src/main/java/com/suwiki/core/model/enums/LectureEvaluationTab.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/exam/ExamEvaluationList.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/LectureEvaluationExtraAverage.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/LectureEvaluationList.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/LectureInfo.kt
  core/ui/src/main/java/com/suwiki/core/ui/extension/LazyListState.kt
  domain/lectureevaluation/viewerreporter/src/main/java/com/suwiki/domain/lectureevaluation/viewerreporter/usecase/lecture/GetLectureEvaluationListUseCase.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationContract.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationScreen.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationViewModel.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/model/MyEvaluationTab.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/navigation/MyEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/build.gradle.kts
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/OnboardingBottomSheet.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/component/StatisticsContainer.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/navigation/LectureEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/src/main/res/drawable/ic_write.xml
  feature/lectureevaluation/viewerreporter/src/main/res/values/strings.xml
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/mypoint/MyPointScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  gradle/libs.versions.toml
  remote/lectureevaluation/my/src/main/java/com/suwiki/remote/lectureevaluation/my/response/MyLectureEvaluationResponse.kt
  remote/lectureevaluation/viewerreporter/src/main/java/com/suwiki/remote/lectureevaluation/viewerreporter/response/exam/ExamEvaluationListResponse.kt
  remote/lectureevaluation/viewerreporter/src/main/java/com/suwiki/remote/lectureevaluation/viewerreporter/response/lecture/LectureEvaluationExtraAverageResponse.kt
Labels: feature

#114 Feature/#113 write evaluation
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiExamReviewContainer.kt
  core/model/src/main/java/com/suwiki/core/model/lectureevaluation/lecture/MyLectureEvaluation.kt
  data/lectureevaluation/editor/src/main/java/com/suwiki/data/lectureevaluation/editor/datasource/RemoteLectureEditorDataSource.kt
  data/lectureevaluation/editor/src/main/java/com/suwiki/data/lectureevaluation/editor/repository/LectureEditorRepositoryImpl.kt
  data/lectureevaluation/viewerreporter/src/main/java/com/suwiki/data/lectureevaluation/viewerreporter/datasource/RemoteExamReportDataSource.kt
  data/lectureevaluation/viewerreporter/src/main/java/com/suwiki/data/lectureevaluation/viewerreporter/repository/ExamReportRepositoryImpl.kt
  domain/lectureevaluation/editor/src/main/java/com/suwiki/domain/lectureevaluation/editor/repository/LectureEditorRepository.kt
  domain/lectureevaluation/editor/src/main/java/com/suwiki/domain/lectureevaluation/editor/usecase/lecture/PostLectureEvaluationUseCase.kt
  domain/lectureevaluation/editor/src/main/java/com/suwiki/domain/lectureevaluation/editor/usecase/lecture/UpdateLectureEvaluationUseCase.kt
  domain/lectureevaluation/viewerreporter/src/main/java/com/suwiki/domain/lectureevaluation/viewerreporter/repository/ExamReportRepository.kt
  domain/lectureevaluation/viewerreporter/src/main/java/com/suwiki/domain/lectureevaluation/viewerreporter/usecase/exam/ReportExamUseCase.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/examevaluation/ExamEvaluationEditorViewModel.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/examevaluation/ExamEvalutionEditorContract.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/examevaluation/ExamEvalutionEditorScreen.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/LectureEvaluationEditorContract.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/LectureEvaluationEditorScreen.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/LectureEvaluationEditorViewModel.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/navigation/EvaluationEditorNavigation.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/navigation/MyEvaluationEditNavigation.kt
  feature/lectureevaluation/editor/src/main/res/values/strings.xml
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationViewModel.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/navigation/MyEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/build.gradle.kts
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailContract.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailViewModel.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/navigation/LectureEvaluationNavigation.kt
  feature/lectureevaluation/viewerreporter/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainNavigator.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/timetable/build.gradle.kts
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/OpenLectureScreen.kt
  remote/lectureevaluation/editor/src/main/java/com/suwiki/remote/lectureevaluation/editor/api/LectureEditorApi.kt
  remote/lectureevaluation/editor/src/main/java/com/suwiki/remote/lectureevaluation/editor/datasource/RemoteLectureEditorDataSourceImpl.kt
  remote/lectureevaluation/viewerreporter/src/main/java/com/suwiki/remote/lectureevaluation/viewerreporter/datasource/RemoteExamReportDataSourceImpl.kt
  remote/lectureevaluation/viewerreporter/src/main/java/com/suwiki/remote/lectureevaluation/viewerreporter/request/ReportExamRequest.kt
Labels: feature

#117 fix/#115 : 내 글 관리 - 데이터 없음 스크린 추가
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationContract.kt
  feature/lectureevaluation/my/src/main/java/com/suwiki/feature/lectureevaluation/my/MyEvaluationScreen.kt
  feature/lectureevaluation/my/src/main/res/values/strings.xml
Labels: bug

#119 Feature/#116 #118 fix null force update
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiClassReviewCard.kt
  core/ui/src/main/java/com/suwiki/core/ui/util/Consts.kt
  data/notice/src/main/java/com/suwiki/data/notice/datasource/RemoteNoticeDataSource.kt
  data/notice/src/main/java/com/suwiki/data/notice/repository/NoticeRepositoryImpl.kt
  domain/notice/src/main/java/com/suwiki/domain/notice/repository/NoticeRepository.kt
  domain/notice/src/main/java/com/suwiki/domain/notice/usecase/CheckUpdateMandatoryUseCase.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/component/StatisticsContainer.kt
  feature/navigator/build.gradle.kts
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainContract.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainViewModel.kt
  feature/navigator/src/main/res/values/strings.xml
  remote/notice/src/main/java/com/suwiki/remote/notice/api/NoticeApi.kt
  remote/notice/src/main/java/com/suwiki/remote/notice/datasource/RemoteNoticeDataSourceImpl.kt
  remote/notice/src/main/java/com/suwiki/remote/notice/response/UpdateMandatoryResponse.kt
Labels: bug, feature

#120 Feature/#89 시간표 데이터베이스 마이그레이션 테스트 코드 작성
  build-logic/convention/src/main/java/DataConventionPlugin.kt
  build-logic/convention/src/main/java/FeatureComposeConventionPlugin.kt
  build-logic/convention/src/main/java/RemoteConventionPlugin.kt
  build-logic/convention/src/main/java/com/kunize/convention/KotlinAndroid.kt
  core/database/build.gradle.kts
  core/database/src/androidTest/java/com/suwiki/database/ExampleInstrumentedTest.kt
  core/database/src/androidTest/java/com/suwiki/database/TimetableDatabaseMigrate1To2Test.kt
  gradle/libs.versions.toml
  local/login/build.gradle.kts
  local/openmajor/build.gradle.kts
  local/timetable/build.gradle.kts
  local/user/build.gradle.kts
Labels: feature

#123 Refactor/#122 컴포넌트, 리소스 분리
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiAlignButton.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/align/SuwikiSelectContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/badge/SuwikiBadge.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/bottomsheet/SuwikiSelectBottomSheet.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/card/SuwikiReviewGradeCard.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/container/SuwikiBoardContainer.kt
  core/designsystem/src/main/java/com/suwiki/core/designsystem/component/filter/SuwikiFilterButton.kt
  core/designsystem/src/main/res/drawable/ic_appbar_add.xml
  core/designsystem/src/main/res/drawable/ic_appbar_list.xml
  core/designsystem/src/main/res/drawable/ic_appbar_setting.xml
  core/designsystem/src/main/res/drawable/ic_star.xml
  core/designsystem/src/main/res/values/strings.xml
  core/ui/src/main/res/drawable/ic_align_checked.xml
  core/ui/src/main/res/drawable/ic_arrow_gray_right.xml
  core/ui/src/main/res/drawable/ic_star_empty.xml
  core/ui/src/main/res/drawable/ic_star_filled.xml
  core/ui/src/main/res/values/strings.xml
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/examevaluation/ExamEvalutionEditorScreen.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/LectureEvaluationEditorScreen.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/SuwikiSlider.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/SuwikiSliderThumb.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/SuwikiSliderThumbWithLabel.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/SuwikiSliderTrack.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/material/Slider.kt
  feature/lectureevaluation/editor/src/main/java/com/suwiki/feature/lectureevaluation/editor/lectureevaluation/component/slider/material/SliderState.kt
  feature/lectureevaluation/editor/src/main/res/values/strings.xml
  feature/lectureevaluation/my/src/main/res/values/strings.xml
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/LectureEvaluationScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/EvaluationAppBar.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/EvaluationCard.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/component/EvaluationSearchBar.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/LectureEvaluationDetailScreen.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/component/ExamEvaluationContainer.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/component/LectureEvaluationContainer.kt
  feature/lectureevaluation/viewerreporter/src/main/java/com/suwiki/feature/lectureevaluation/viewerreporter/detail/component/StatisticsContainer.kt
  feature/lectureevaluation/viewerreporter/src/main/res/drawable/ic_filter.xml
  feature/lectureevaluation/viewerreporter/src/main/res/drawable/ic_filter_arrow_down.xml
  feature/lectureevaluation/viewerreporter/src/main/res/values/strings.xml
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/banhistory/BanHistoryScreen.kt
  feature/myinfo/src/main/java/com/suwiki/feature/myinfo/myaccount/MyAccountScreen.kt
  feature/myinfo/src/main/res/values/strings.xml
  feature/navigator/src/main/java/com/suwiki/feature/navigator/MainScreen.kt
  feature/navigator/src/main/java/com/suwiki/feature/navigator/component/SuwikiToast.kt
  feature/notice/src/main/java/com/suwiki/feature/notice/NoticeScreen.kt
  feature/openmajor/src/main/java/com/suwiki/feature/openmajor/component/OpenMajorContainer.kt
  feature/openmajor/src/main/res/drawable/ic_filter_stared.xml
  feature/openmajor/src/main/res/values/strings.xml
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/OpenLectureScreen.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/openlecture/component/OpenLectureCard.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/timetable/component/timetable/Common.kt
  feature/timetable/src/main/java/com/suwiki/feature/timetable/widget/timetable/Common.kt
  feature/timetable/src/main/res/values/strings.xml
Labels: refactor
